### ISSUE TITLE
PackageManager.service.validateSignature(signature)

### ISSUE THREAD

**Issue by koreaflash** [distriqt/ANE-PackageManager#10]
PackageManager.service.validateSignature(signature)
What value should be entered for "signature" in the above code...?
Is there a corresponding value in the image you are attaching?
![keytool](https://github.com/distriqt/ANE-PackageManager/assets/36652089/1339e2fb-5dfc-4880-ab12-e914fb3b283b)

**Comment by marchbold** [comment]
Hi, It's currently using the base64 encoded value of the signature which isn't shown in the keytool output you have listed. 

However I have an update awaiting final testing that allows you to use the sha1 hex signature from this output (without the colons). 

https://drive.google.com/file/d/1f1-TqssEEwOCBwe5_cVwV_yPFu0hX3WO/view?usp=sharing

Let me know how it goes.

**Comment by koreaflash** [comment]
Version v3.4.1 works well.
Thank you.
