### ISSUE TITLE
Error:         uses-sdk:minSdkVersion 21 cannot be smaller than version 23

### ISSUE THREAD

**Issue by raresn** [distriqt/ANE-PackageManager#12]
Just configured a fresh project and i get this, any clue @marchbold ?

d:\APM>apm generate app-descriptor src/MyApp-app.xml
Android package name: air.ro.fxstudio.agenda
⣾ Android manifest merging
✗ Android manifest merge
generate/app-descriptor :: d:\APM\.tmp909608\AndroidManifest.xml:4:5-74 Error:
        uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library d:\APM\apm_packages\com.distriqt.firebase.Auth\contents\platforms\android\firebase-auth-23.0.0\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="com.google.firebase.auth" to force usage (may lead to runtime failures)

**Comment by raresn** [comment]
hmm, or should i post this here: https://github.com/airsdk/apm ?

**Comment by raresn** [comment]
FIX:
apm generate config android
edit file in config\android\AndroidManifest.xml
put sdk 23
apm generate app-descriptor

**Comment by marchbold** [comment]
@raresn Glad you found the solution, I'm aiming to have a minimum sdk version option as a config option in apm but currently you need to set this manually via the config process you found. Cheers
