### ISSUE TITLE
getUserApps get list of installed user apps 

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-PackageManager#4]
I really need this method into your ANE.
Earlier I used https://github.com/jakehilton/PackageManagerANE
But after mitrition to AIR SDK 33 + 64 bit I can't use it.

This  method is into https://github.com/myflashlab/packageManager-ANE
But I use many your ANEs. And I don't want to use ANEs from different develpers into my app.

Can you integrate this methods (getUserApps and getSystemApps) into your ANE?

**Comment by marchbold** [comment]
Definitely, I'll get this added asap.

**Comment by Dima107** [comment]
thank you
I know that this feature woks on Android.
Is it possible to do same for IOS?

**Comment by marchbold** [comment]
As far as I'm aware this isn't possible on iOS. iOS locked down apps knowing about what other apps are installed early on. 

Best you can do is use the query schemes. You need to add the schemes you want to query to your info additions and then on a device you can use `Share.service.applications.isInstalled()` function in the Share ANE to query the scheme:

https://distriqt.github.io/ANE-Share/asdocs/com/distriqt/extension/share/Applications.html#isInstalled()

**Comment by marchbold** [comment]
I've added this into the latest release:

https://github.com/distriqt/ANE-PackageManager/wiki/u.Installed-Application-Info

Let me know if you have any issues.
