### ISSUE TITLE
What is the minimum Android version supported?

### ISSUE THREAD

**Issue by koreaflash** [distriqt/ANE-PackageManager#5]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this packagemanager and ask your question.

I tested on Android 4.4.2 (SM-T530) and 6.0.1 (SM-T536), but it does not run normally. As soon as the app is launched, it quits.
I confirmed that it runs normally in Android 8.0.1.

##### Expected behaviour
It should run normally on Android 4.4.2 and 6.0.1.

##### Actual behaviour
It does not run normally on Android 4.4.2 and 6.0.1.
As soon as the app is launched, it quits.

##### Environment 

- AIR SDK version: 33.1.1.144
- Device OS: Anroid
- Device version: 4.4.2 / 6.0.1
- Development IDE: FlashBuilder 4.7
- Development OS: Windows 10

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Can you post the logs from the device when the crash occurs?

https://docs.airnativeextensions.com/docs/tutorials/device-logs

**Comment by koreaflash** [comment]
Attach log file.
For reference, the test application ID is "air.com.distriqt.test".
Thank you.
[SM-T530.log](https://github.com/distriqt/ANE-PackageManager/files/6388266/SM-T530.log)
[SM-T536.log](https://github.com/distriqt/ANE-PackageManager/files/6388267/SM-T536.log)

**Comment by koreaflash** [comment]
The previous version, Air SDK 33.1.1.406, works normally.
There seems to be a problem with the Air SDK 33.1.1.444.

**Comment by marchbold** [comment]
Yep looks like this is an AIR SDK issue and not related to this extension.

This issue may be related: https://github.com/Gamua/Adobe-Runtime-Support/issues/783

I suggest you post these logs and your issue on that issue tracker to make sure Harman are aware:

https://github.com/Gamua/Adobe-Runtime-Support/issues
