### ISSUE TITLE
Main app shutdown when I check install from unknown source in app settings

### ISSUE THREAD

**Issue by rzv86** [distriqt/ANE-PackageManager#7]
It happens when I target app to sdk 30 in android manifest and  install it on android 11(sdk30) device. 
Targeting to sdk 30 and installing on android 10 and lower devices works fine.
Targeting to sdk 29 all seems to work fine in every way.

##### Expected behaviour
Open app settings to check install from unknown source. After that it needs to jump back to main app.

##### Actual behaviour
Open app settings to check install from unknown source. App shutdown itself just after I press the install unknown source button.

##### Environment 

I have harmann licence, sdk 33.1.1.633, Adobe Animate.

##### Logs
No logs, just silent shutdown

Device logs if relevant

**Comment by marchbold** [comment]
Can you grab the logs from the device? There should be some reason logged for the termination of the app.

https://docs.airnativeextensions.com/docs/tutorials/device-logs

**Comment by rzv86** [comment]
Replaced domain and app name with: air.myCompany.myApp
I used cmd command for generating log:
 C:\AIR_SDK_33.1.63\lib\android\bin\adb.exe logcat air.myCompany.myApp:I ActivityManager:I *:S

I've tried to cut down all the unnecesary code from log.
[samsung a71 activity2.txt](https://github.com/distriqt/ANE-PackageManager/files/7582041/samsung.a71.activity2.txt)


I also used C:\AIR_SDK_33.1.63\lib\android\bin\adb.exe logcat  command, but the log is so long and I didn't got what I needed.

**Comment by marchbold** [comment]
Nothing obvious there, the system is stopping your app. This could be the new process in android 11. I'll setup some tests to replicate.

**Comment by rzv86** [comment]
One more thing, I've just made a simple app in java (android studio), using the `startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, Uri.parse("package:your.application.package")));` ,  target sdk 30, and works fine, app doesn't restart.
Maybe the Air SDK needs to be updated, should I send this issue also to harman?

**Comment by marchbold** [comment]
Hi, I've been looking through this and as far as I understand when you change permissions like this, Android won't restart a simple activity but will restart services which may cause an activity to be restarted if it is tied to a service. This is highly likely in an app that is more than just a simple one. 

I don't think there's anything we can do from the ANE side here. This seems to be solely related to the AIR activity and the Android system.   

You could report it to Harman and see if it's something they'll look into. 

However there are a few of these "restart" type scenarios around permission changes now so it might be better if you just design around it?
