### ISSUE TITLE
Error # Need to declare android.permission.REQUEST_INSTALL_PACKAGES to call this api

### ISSUE THREAD

**Issue by lwmirkk** [distriqt/ANE-PackageManager#8]
I only use this call in Package Manager:
`PackageManager.service.getInstallerPackageName();`

Question: is the "REQUEST_INSTALL_PACKAGES" permission really needed
to use in this call?

I ask this because now Google is more annoying with apps that need the permission : REQUEST_INSTALL_PACKAGES
And I would even take out this permission, but I get this error when using this function of this ANE.

Can I continue to use this call even without this permission? (and returning this error, but working)
Or I need this permission?

Thanks a lot. =)

**Comment by marchbold** [comment]
That permission is only required if you are planning on using the "install application" functionality:

https://docs.airnativeextensions.com/docs/packagemanager/installing-apps

It isn't required for the installer package name.

**Comment by marchbold** [comment]
When exactly does the error occur? I'll look into it.

**Comment by lwmirkk** [comment]
> When exactly does the error occur? I'll look into it.

When calling this:
`PackageManager.service.canRequestApplicationInstalls`
and not declare the permission.

For me won't be a problem, cause I will delete this line and won't use this check and permission anymore. =)

**Comment by marchbold** [comment]
Yes that is expected. 

`canRequestApplicationInstalls` checks the presence of the `REQUEST_INSTALL_PACKAGES` as it's checking if your app has this permission which is required to install applications.
